### ISSUE TITLE
 Update README with Camunda Community Hub badges

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/dmn-scala#151]
Hello!

Could you please add the appropriate labels for lifecycle stage and which Camunda product(s) your repo is compatible with? You can find these badges and more information [here in our documentation](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md).

Thank you!

**Comment by saig0** [comment]
@xomiamoore thank you for raising this up. :+1: 

Please note that the DMN engine is not a community project anymore. It is now an official Camunda project. We need to move the project out of the community hub and adjust the README page.

**Comment by xomiamoore** [comment]
Ah, good to know, I didn't realize. Definitely should put it in the correct place then. Let me know if there's anything I can do to help!
