### ISSUE TITLE
DMN literal expression : handling regular expressions

### ISSUE THREAD

**Issue by younes-io** [camunda-community-hub/dmn-scala#24]
Hello,

I'm trying to process some text using regular expressions, so I handled it like this :

![image](https://user-images.githubusercontent.com/3153107/114360048-e4149d80-9b74-11eb-8820-8cce316b7655.png)

However, when I deploy the DMN file, this is the log I get :

`06:51:51.053 [main] WARN org.camunda.dmn.DmnEngine - Failure(Fail to parse file 'test_js.dmn': Failure(Expression language 'javascript' is not supported))`

It seems that the DMN Engine worker does not support JS.

Am I missing some setup ? Is there a better way to do this ?

Thank you for your help,

**Comment by saig0** [comment]
Correct. Currently, the DMN engine supports only FEEL - no other expression languages.

In most cases, it should be possible to write the expression also in FEEL.

This was also raised in the forum: https://forum.camunda.io/t/zeebe-dmn-worker-literal-expression-in-javascript-not-supported/2159/3

**Comment by vincentgiraud** [comment]
DMN regex test with FEEL: https://forum.camunda.io/t/zeebe-dmn-worker-literal-expression-in-javascript-not-supported/2159/4?u=vincentgiraud

**Comment by saig0** [comment]
I close this issue under the assumption that the question is answered. Please reopen the issue if there are still open questions to this topic :balloon:
