### ISSUE TITLE
FEEL 1.3 namespace is not supported

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/dmn-scala#64]
If I parse a DMN contains an expression with the FEEL 1.3 namespace `https://www.omg.org/spec/dmn/20191111/feel/` then it fails.

Failure message:
```
Expression language 'https://www.omg.org/spec/dmn/20191111/feel/' is not supported
```

It seems that the FEEL namespace of version 1.3 (and 1.2) is not supported.

DMN engine version `1.6.2`

**Comment by falko** [comment]
Oops
